export const API_PATHS = {
  USER_LOGIN: "/user/login",
  USER_REGISTER: "/user/register",
  USER_LOGOUT: "/user/logout",
  USER_LIST: "/user/list",
  USER_DETAIL: (id: string) => `/user/detail/${id}`,
  EMAIL_SEND_CODE: "/email/sendCode",
  TEMPLATE_LIST: "/template/list",
  TEMPLATE_CREATE: "/template/create",
  TEMPLATE_UPDATE: "/template/update",
  TEMPLATE_DELETE: "/template/delete",
  CONFIGURATION_LIST: "/configuration/list",
  CONFIGURATION_DETAIL: (id: string) => `/configuration/detail/${id}`,
  CONFIGURATION_CREATE: "/configuration/create",
  CONFIGURATION_UPDATE: "/configuration/update",
  CONFIGURATION_DELETE: "/configuration/delete",
  SERVER_LIST: "/server/list",
  SERVER_DETAIL: (id: string) => `/server/detail/${id}`,
  SERVER_CREATE: "/server/create",
  SERVER_UPDATE: "/server/update",
  SERVER_DELETE: "/server/delete",
  SERVER_TEST_CONNECTION: (id: string) => `/server/test-connection/${id}`,
  MESSAGE_LIST: "/message/list",
  MESSAGE_DETAIL: "/message/detail",
  MESSAGE_CREATE: "/message/create",
  MESSAGE_UPDATE: "/message/update",
  MESSAGE_DELETE: "/message/delete",
  MESSAGE_SEND: "/message/send",
  MESSAGE_MY_LIST: "/message/my/list",
  MESSAGE_MY_DETAIL: "/message/my/detail",
  MESSAGE_MY_READ: "/message/my/read",
  APPROVAL_TEMPLATE_LIST: "/approval-template/list",
  APPROVAL_TEMPLATE_DETAIL: (id: string) => `/approval-template/detail/${id}`,
  APPROVAL_TEMPLATE_CREATE: "/approval-template/create",
  APPROVAL_TEMPLATE_UPDATE: (id: string) => `/approval-template/update/${id}`,
  APPROVAL_TEMPLATE_DELETE: (id: string) => `/approval-template/delete/${id}`,
  APPROVAL_POLICY_LIST: "/approval-policy/list",
  APPROVAL_POLICY_DETAIL: (id: string) => `/approval-policy/detail/${id}`,
  APPROVAL_POLICY_CREATE: "/approval-policy/create",
  APPROVAL_POLICY_UPDATE: (id: string) => `/approval-policy/update/${id}`,
  APPROVAL_POLICY_DELETE: (id: string) => `/approval-policy/delete/${id}`,
  APPROVAL_LIST: "/approval/list",
  APPROVAL_DETAIL: (id: string) => `/approval/detail/${id}`,
  APPROVAL_CREATE: "/approval/create",
  APPROVAL_CANCEL: (id: string) => `/approval/cancel/${id}`,
  APPROVAL_APPROVE: (id: string) => `/approval/${id}/approve`,
  APPROVAL_REJECT: (id: string) => `/approval/${id}/reject`,
  APPROVAL_TRANSFER: (id: string) => `/approval/${id}/transfer`,
  APPROVAL_ADD_APPROVER: (id: string) => `/approval/${id}/add-approver`,
  APPROVAL_TASK_MY_PENDING: "/approval-task/my/pending",
  APPROVAL_TASK_MY_DONE: "/approval-task/my/done",
} as const;
